function parsave_SVD_STRESS(NAME_WS_STORE,SNAP_STRESSES,SingleV_STRESS,PHI_STRESS,V_STRESS)

% parsave_SVD_U(NAME_WS_STORE,SNAP_DISP{igroup},SingleV_DISP,PHI_DISP,TRAJECTORIES,list_snapshots_show,NAME_SCRIPT);
% parsave_SVD_STRESS(NAME_WS_STORE,SNAP_STRESSES{igroup},SingleV_STRESS,PHI_STRESS,V_STRESS)

save(NAME_WS_STORE,'SNAP_STRESSES','SingleV_STRESS','PHI_STRESS','V_STRESS','-append') ;

end